print('Enter the first number to add:')
first = input()
print('Enter the second number to add:')
second = input()
print('Enter the third number to add:')
third = input()
sum = int(first) + int(second) + int(third)
print('The sum is ' + str(sum))
print('The sum is ' + first + second + third)